### PR TITLE
Added PlayStation Classic controller mapping for Windows

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Just like in title - PS Classic mapping made from Steam Big Picture.

Mapping has been created by Marioysikax.

### CODE REVIEW

**Comment by p-groarke** [comment]
No hats?

**Comment by CookiePLMonster** [comment]
Nope.

image

**Comment by p-groarke** [comment]
I know the controller, the dpad should be hats.

**Comment by CookiePLMonster** [comment]
Oh my bad sorry, I'll relay this back.

**Comment by p-groarke** [comment]
I'm guessing this is coming through some sort of adapter. Could be the adapter sending axis input... But yes, please double check. Thx.

**Comment by CookiePLMonster** [comment]
It may not look like this, but those connectors are standard USB, so no adapters are required.

**Comment by p-groarke** [comment]
I had no idea, nice. Then yeah, it should probably be hats.

**Comment by offalynne** [comment]
yeah it’s ‘dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1’

**Comment by offalynne** [comment]
yeah it’s ‘dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1’

**Comment by Marioysikax** [comment]
Yeah, the string was not generated with Steam Big Picture but rather SDL2 gamepad tools. The tool just gets to the end with nothing unusal cropping up. 

It turns out the controller does not have d-pad, but d-pad is instead two axis. 
DiscordPTB_epitQY4mLJ
And because of this, Steam Big Picture actually doesn't allow the d-pad, only way to bind the controller is to bind the d-pad into left stick instead. 
Steam_L2RS6ZubE3
Binding d-pad into left stick gives following string: 
`030000004c050000da0c000000000000,PlayStation Classic Controller,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,lefttrigger:b4,righttrigger:b5,`

So the string that offalynne provided above is the one that works and correctly binds the controllers d-pad into d-pad and that also shows up correctly with SDL2 Gamepad Tool now when testing the controller. 
`030000004c050000da0c000000000000,PlayStation Classic Controller,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b6,rightshoulder:b7,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,lefttrigger:b4,righttrigger:b5,`

**Comment by CookiePLMonster** [comment]
Updated with the mapping with hats mapped.

**Comment by p-groarke** [comment]
The mystery has been solved. Aaaaaand merge :)

Thx everyone for pitching in on this one, and for such a robust explanation of what was going on.

**Pull request merged**
