### PR TITLE
Add Google Stadia Controller mappings for Windows

### PR DESCRIPTION
**Pull request by Chris--B**
I used SDL2 Gamepad tool to generate this, since I didn't see it listed online anywhere.

### CODE REVIEW

**Comment by offalynne** [comment]
can you double check the axis results on sticks? map looks incorrect.

**Comment by Chris--B** [comment]
What about it looks incorrect? I double checked with the Gamepad tool and got the same results, but I have a sample SDL app that never gets GameController events. I'm debugging that currently.

**Comment by offalynne** [comment]
The stick axes are extremely weird; no other Windows device maps like that. Sometimes another non-zero analogue input during mapping can create mistakes that resemble this with the tool. If you've tested this map and it's correct, then I guess it's just weird!

**Comment by Chris--B** [comment]
I haven't gotten the controller to work outside of the tool, so I think you're right and there's something weird here. I'll try using it in some Steam games and see if I can get anywhere.

Here are another two mappings from just now. They're subtly different from the last one, but I'm not sure if it's meaningful.
```
03000000d11800000094000000000000,Stadia Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:b12,righttrigger:b11,
03000000d11800000094000000000000,Stadia Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,-lefty:-a1,+lefty:+a2,rightx:a3,-righty:-a4,+righty:+a5,lefttrigger:b12,righttrigger:b11,
```

**Comment by Chris--B** [comment]
I was able to fix my SDL sample app (it was an issue on my end) and I can now see GameController events. I definitely  think you're right - the right stick acts funny. I can't quite describe the issue that I see. It's just odd. Negative y points up - is that normal?

I'm still using the mapping from the PR, not the other ones I posted.

**Comment by p-groarke** [comment]
@Chris--B Can you try with this one? It looks ok to me.
```
03000000d11800000094000000000000,Stadia Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:b12,righttrigger:b11,
```

**Comment by offalynne** [comment]
> Negative y points up - is that normal?

if i understand you correctly, yes. if you have another device that’s already in the db perhaps you could try it out to compare?

**Comment by Chris--B** [comment]
Yeah, that mapping acts right. Left and right sticks give similar numbers in similar positions now. I'll update the PR with that one.

**Comment by p-groarke** [comment]
Thx for taking the time to debug this.

**Comment by aaronfranke** [comment]
Note that Stadia Controller mappings are now in upstream SDL2, see https://hg.libsdl.org/SDL/rev/f337f1e13756

Mappings for Mac and Linux will be pulled on the next SDL2 release.

**Pull request merged**
