### PR TITLE
Added new entry for Sidewinder Game Pad USB on Linux.

### PR DESCRIPTION
**Pull request by MichaelChampigny**
This is a new GUID entry for a Microsoft Sidewinder Game Pad USB device, tested on Linux. There appear to be several Sidewinder models made by Microsoft over the years, and this one is quite old.

### CODE REVIEW

**Comment by offalynne** [comment]
Thank you for the PR! Can you link an image that matches the product?

**Comment by MichaelChampigny** [comment]
Sure thing. This is the exact model. Note that there are only 2 buttons in the center marked with a "." and ".." for (I guess) "Mode" and "Start/Back". I did the best I could with the mapping given the 6 main button cluster on the right. I mapped the shoulder buttons as "triggers" since that is how they are marked on the packaging.

https://twitter.com/NLightsRetro/status/1307005992224391170/photo/1
https://www.amazon.com/Microsoft-SideWinder-Game-Pad-USB/dp/B000069JX9
https://www.spinpoint.org/imperium/database.php?action=1&entry=42

**Comment by offalynne** [comment]
Thanks, can you clarify how you mapped the 2 rightmost face buttons ("C" and "Z")?

**Comment by MichaelChampigny** [comment]
> Thanks, can you clarify how you mapped the 2 rightmost face buttons ("C" and "Z")?

Sure, it was awkward mapping 6 buttons to act like an XBox gamepad. I think what I sent you is incorrect. I used the antimicrox tools to get the mapping, but it looks like it didn't save my settings. I will retest, but this is basically what I had:

A b1
B b2
X b4
Y b5
Start b10 // Marked "."
Back b9   // Marked ".."
Left Trigger b7
Right Trigger b8
Left Stick X Axis 1
Left Stick Y Axis 2
Left Shoulder b6  // Marked "C" on face
Left Shoulder b3  // Marked "Z" on face

I'm not sure how to load a text file with just this one setting in antimicrox to test this, as I could just manually edit that file and reload to test. It's easier to edit the file to make changes than clicking around on the GUI.

**Comment by MichaelChampigny** [comment]
> Thanks, can you clarify how you mapped the 2 rightmost face buttons ("C" and "Z")?

Fixed on latest commit. I used a different tool _gamepad-tool_ from SDL2 to perform the mapping, and I was able to extract the string. These mappings look good (verified). Z and C were mapped to left shoulder and right shoulder.

**Comment by offalynne** [comment]
Thanks! We use the Hori Fighting Commander layout for 6 button pads: <https://i.imgur.com/zNbfJVd.png> I'll modify the map to match.

**Comment by offalynne** [comment]
> leftbumper

whups, fixed

**Pull request merged**
