### PR TITLE
Update gamecontrollerdb.txt

### PR DESCRIPTION
**Pull request by 8BitDo**
* Added 8BitDo Ultimate Wired Controller (Dinput)
* Fixed 8BitDo Ultimate 2.4g Wireless Controller Mapping Error (Dinput)

### CODE REVIEW

**Comment by offalynne** [comment]
> Fixed 8BitDo Ultimate 2.4g Wireless Controller Mapping Error (Dinput)

All that's changed is removing the paddles. Do you not want the paddles mappings included?

**Comment by offalynne** [comment]
@8BitDo can you confirm good after my change ?

**Comment by offalynne** [comment]
@8BitDo can you confirm good after these changes ?

**Comment by 8BitDo** [comment]
> @8BitDo这些变化后你能确认好吗？

Yes, we have tested.

**Pull request merged**
