### PR TITLE
fix 8Bitdo SF30 Pro in Linux

### PR DESCRIPTION
**Pull request by joseluis**
changes:
- `lefttrigger:a5` → `leftrigger:b8`
- `righttrigger:a4` → `rightrigger:b9`

### CODE REVIEW

**Comment by offalynne** [comment]
This will kill analogue, can you confirm you're on the latest firmware, and see if you can get axis values? You can get the axis values by pressing lightly when using the configuration tool, or test with jstest-gtk.gitlab.io or equivalent and manually edit the map.

**Comment by offalynne** [comment]
@8BitDo

**Comment by 8BitDo** [comment]
Okay, we are not yet familiar with GNU/Linux, and it will take a while to check this issue. thanks.

**Comment by joseluis** [comment]
> This will kill analogue, can you confirm you're on the latest firmware, and see if you can get axis values? You can get the axis values by pressing lightly when using the configuration tool, or test with jstest-gtk.gitlab.io or equivalent and manually edit the map.

sorry for the delay in responding, I'm on firmware 1.33 (latest is 1.38) since I've been unable to update the controller from linux.

Before these changes I had wrong reports for those axis values. I did use `gamepadtool` to get the right values.

**Comment by offalynne** [comment]
@joseluis you should be able to update the firmware from Linux fine using fwupd: https://github.com/fwupd/8bitdo-firmware

> I did use gamepadtool to get the right values.

Those are button mappings. The triggers are analogue. Pull lightly while mapping, or use jstest-gtk.gitlab.io or equivalent and manually edit the map.

**Comment by offalynne** [comment]
@joseluis @8BitDo since it's been a month without reply here I'm going to close this PR, if you're able to confirm an improved mapping with up to date firmware, or can confirm that on up to date firmware with this GUID, the analogue triggers return only digital results making this mapping correct, feel free to reply here or submit a new issue or PR.

**Pull request closed without merging**
