### PR TITLE
Adding iCode Retro USB adapters

### PR DESCRIPTION
**Pull request by alijani1**
I am the creator of the popular iCode Retro USB Adapters that let you use classic controllers like Atari, Colecovision, Sega controllers with your emulators.  [https://www.icode.com/product-category/gaming/gaming-adapters/](see icode.com)

I added the iCode adapter configurations to support many platforms like the c64mini/maxi.  please merge.  thank you!

### CODE REVIEW

**Comment by offalynne** [comment]
Great, thank you ! Unfortunately it looks like you've copied the mappings across platforms from Linux without actually authoring and testing on those platforms. Each platform is different, and you should not assume GUID will match, nor buttons or axes enumerate the same. Please revise your PR with mappings authored and tested per platform, or remove mappings for any platforms you are personally unable to cover.

Thanks again !

**Comment by offalynne** [comment]
Hm, I'm further disincentivized to include this mapping based on the GUID, you seem to be reusing a common vendor and product ID which is used across multiple open source products and I am skeptical there is a correct unified mapping across them: https://github.com/search?q=0x3013+product&type=code

**Comment by offalynne** [comment]
I have corrected the Windows GUID format and removed invalid Mac and Android mappings. Feel free to open a PR in the future if you want to contribute support for those platforms and are able to author and test them as required.

**Comment by alijani1** [comment]
> I have corrected the Windows GUID format and removed invalid Mac and Android mappings. Feel free to open a PR in the future if you want to contribute support for those platforms and are able to author and test them as required.

Thank you. The main one we needed was Linux.

**Pull request merged**
