### PR TITLE
Add 3dRudder controller

### PR DESCRIPTION
**Pull request by Mvivant**

### CODE REVIEW

**Comment by D0NM** [comment]
have you seen this new repo ? https://github.com/p-groarke/SDL_GameControllerDB

**Comment by Mvivant** [comment]
no is it good?

**Comment by D0NM** [comment]
It is well maintained.
And it has all the available mappings.

**Comment by D0NM** [comment]
It is a well maintained source where you can get all the recent mappings.

**Comment by D0NM** [comment]
I was wrong. The provided repo has a new SDL 2.5 formatted data.
It stopped working for my LOVE2D stuff.

**Comment by p-groarke** [comment]
Checkout the release 2.0.4 for the old version (before converting the db).

**Pull request merged**
