### PR TITLE
Fix Razer Raiju Tournament Edition Linux

### PR DESCRIPTION
**Pull request by khalilgharbaoui**
Previous extraction of both the wireless and wired versions was done with an older unsupported tool!
Which caused it to randomly shoot at things in games :p
I extracted it properly now using SDL2 Gamepad Tool 1.2 which works perfectly.

### CODE REVIEW

**Comment by khalilgharbaoui** [comment]
@offalynne button mappings were wrong so i fixed those...

I noticed last time you fixed my GUID back in: https://github.com/gabomdq/SDL_GameControllerDB/pull/486

I think this time those are valid right?

**Comment by offalynne** [comment]
Great ! Can you remove the second map (GUID ending int 6800) please ? That one uses a standard mapping and should be unnecessary —- SDL is already handling it internally, see #478. Thanks !

**Comment by khalilgharbaoui** [comment]
@offalynne i made those zeros as you requested... but previous time the 1 in front you also made a 0...
```
03000000321500000710000000010000
```
VS what i have now:
```
03000000321500000710000001010000
```
Is that still OK?

**Comment by offalynne** [comment]
The first GUID is fine. Please remove the second map altogether as SDL does not need the map since it is already correctly handled internally.

**Comment by khalilgharbaoui** [comment]
OK i remove the wired mapping altogether... even though i see some differences in the mappings...

wireless: `a:b1,b:b2,x:b0,y:b3,back:b8,guide:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,...`
wired:     `a:b0,b:b1,x:b2,y:b3,back:b4,guide:b15,start:b6,leftstick:b7,rightstick:b8,leftshoulder:b9,rightshoulder:b10...`

But its OK if you say its OK... I also give it a try after its merged and if does not work ill make PR again:

Leaving original raw extraction here for convenience:
```
05000000321500000a10000001000000,Razer Raiju Tournament Edition,platform:Linux,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,

03000000321500000710000001016800,Razer Raiju Tournament Edition Wired,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b4,guide:b15,start:b6,leftstick:b7,rightstick:b8,leftshoulder:b9,rightshoulder:b10,dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,
```

Hope its good now?

**Comment by offalynne** [comment]
> i see some differences in the actual mappings

The second mapping `a:b0, […]` matches SDL’s internal map so all should be well. It is not unusual that wired/wireless modes are a bit different.

Thanks !

**Comment by khalilgharbaoui** [comment]
> > i see some differences in the actual mappings
> 
> The second mapping `a:b0, […]` matches SDL’s internal map so all should be well. It is not unusual that wired/wireless modes are a bit different.
> 
> Thanks !

Ok that makes sense... le

**Comment by khalilgharbaoui** [comment]
Yes that makes sense now...
I closed the PR by accident.. and reopened.
Please accept 😄

**Pull request merged**
