### PR TITLE
Xbox Series X Controller,platform:Linux

### PR DESCRIPTION
**Pull request by paroj**

### CODE REVIEW

**Comment by offalynne** [comment]
Duplicate of L330

**Comment by paroj** [comment]
you mean this?
https://github.com/gabomdq/SDL_GameControllerDB/blob/7db5153593f90479c5f16791830115231f079334/gamecontrollerdb.txt#L330

**Comment by offalynne** [comment]
Typo, L1330

https://github.com/paroj/SDL_GameControllerDB/blob/6ba2b7e58263ceab1930e1d00afb7b6923e23091/gamecontrollerdb.txt#L1330

**Comment by offalynne** [comment]
Typo. L1338.
 https://github.com/gabomdq/SDL_GameControllerDB/blob/7db5153593f90479c5f16791830115231f079334/gamecontrollerdb.txt#L1338

**Comment by paroj** [comment]
just wrote a script to diff the entries. My variant has `'misc1:b15',` which the other one lacks. I guess thats the share button:



is that an error in the entry, or does that entry refer to the old controller?

**Comment by offalynne** [comment]
The PID matches the new device so your `misc1` field is indeed useful data. I’ll add it shortly.

**Pull request closed without merging**
