### PR TITLE
added different version of Sony DualShock 4 (Linux)

### PR DESCRIPTION
**Pull request by oncer**
For some reason, my DS4 was not being recognized, it has a slightly
different GUID.
I copied the mapping from Steam big picture mode.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
It's most likely DS4 v2 from PS4 Slim?

**Comment by oncer** [comment]
I bought the controller in late 2014, so I don't think it belongs to the PS4 slim. I have 4 of those, and I just checked, they all have the same GUID (030000004c050000c405000011810000).

**Comment by mathieu-lemay** [comment]
I also have two of these controllers. Got them both in early 2014, so definitely not PS4 Slim.

**Comment by p-groarke** [comment]
Added, thanks for the PR!

**Pull request closed without merging**
