### PR TITLE
Genesis Adapter for macOS & Windows, Tomee SNES & NES Adapters for Windows, name tweaks

### PR DESCRIPTION
**Pull request by stevenjamescox**
- Adds Retro Bit Sega Genesis Controller Adapter for macOS (`03000000921200004547000000020000`) and Windows (`03000000921200004547000000000000`)
  - It looks like this: 
product-boxsome_online_picture
  - This adapter also technically works with Atari and Commodore 64 controllers (same 9-pin D-Sub connector). I don't have either so I can't check whether these mappings made from a Genesis 6B are proper supersets for 'em.
 - Adds Tomee NES `03000000571d00002100000000000000` & SNES Controller `03000000571d00002000000000000000` adapters for Windows

### CODE REVIEW

**Comment by offalynne** [comment]
> `Adapter`
🤭

**Comment by offalynne** [comment]
Looks good, thank you !

**Comment by offalynne** [comment]
image

adapt ... or? 🤯

**Comment by stevenjamescox** [comment]
Holy crap! I don't recall l _ever_ seeing that spelling in use. When I first saw this, I was certain that Sony had printed a misspelling. I am truly shocked to discover that both `adapter` and `adaptor` are valid spellings. My mind is blown. English is a trip—an insane mishmash.

**Comment by stevenjamescox** [comment]
Oh gosh, I'm sorry for not checking whether the Tomee adapter GUIDs for Windows were already in the database. My bad.

**Pull request merged**
