### PR TITLE
Xbox Series S Controller

### PR DESCRIPTION
**Pull request by viniciusjarina**

### CODE REVIEW

**Comment by viniciusjarina** [comment]
ping @offalynne ?

**Comment by offalynne** [comment]
@viniciusjarina hello ! i have this device sitting in unopened mail at my home office so i figured i’d wait a week or so until i can confirm the mapping myself and contribute the Linux and Android maps as well. if you don’t want to wait i can merge
now and check later, without access to the device to be sure the map lgtm.

**Comment by viniciusjarina** [comment]
Sure no problem 😉  Just to be sure the PR didn't pass unnoticed

**Comment by ejuarezg** [comment]
I can confirm that the Linux mapping is exactly the same as the Mac OS X one. Except, of course, for the GUID.

**Comment by viniciusjarina** [comment]
@ejuarezg  can you paste the GUID you got on the linux? I will update the PR
Thank you

**Comment by ejuarezg** [comment]
Of course, here it is:

050000005e040000130b000005050000

**Pull request closed without merging**
