### PR TITLE
Add Linux mapping for Nintendo Switch Online N64 Controller

### PR DESCRIPTION
**Pull request by dephekt**
GUID 050000007e050000192000000180000014068217, model R-C-NIN-HAC-043. This particular controller used to make the mapping was for the Japanese market.

### CODE REVIEW

**Comment by dephekt** [comment]
NB: This required using the `hid-nx-dkms` [driver](https://github.com/emilyst/hid-nx-dkms) for everything to work as expected.

**Comment by offalynne** [comment]
Thank you!

Please clean up the incorrect `rightx` mappings, and add `guide` and `misc1` mappings for the home and screenshot buttons respectively, or leave a comment with the values and I can make the edit.

**Comment by dephekt** [comment]
Sure, can you clarify what you mean in regards to the incorrect rightx/righty mappings? I'm not clear on what is wrong with them.

There's a guide mapping already for home. I will do the misc1 mapping though.

**Comment by offalynne** [comment]
> can you clarify what you mean in regards to the incorrect rightx/righty mappings [...] guide mapping 

Revisiting this they look fine, I thought they looked incorrect at first glance

> _Sorry, first time doing this._

No problem !

Please provide the index for the screenshot button (by commit or comment) and I'll take care of the rest ! Thanks.

**Comment by offalynne** [comment]
Note that a mapping from [this tool](http://www.generalarcade.com/gamepadtool/) is much preferred to AntiMicroX which is using an older SDL2 and/or is just generally very buggy wrt authoring mappings.

**Comment by dephekt** [comment]
Amended the previous commit to add the misc1:b12 mapping and fix the GUID based on what Gamepad Tool is reporting.

**Comment by dephekt** [comment]
I just noticed there's a mistake here. There's no trailing comma at the end of the line. When I tried using this file with Ship of Harkinian I noticed it didn't seem to be working (it was behaving as if the new config line just wasn't there). When I add the trailing comma it works as expected.

Should I make a new PR to fix it or do you want to just force push an amended commit to master or how would you prefer to deal with it? @offalynne ?

**Comment by offalynne** [comment]
Whatever works!

**Comment by offalynne** [comment]
d86d9432c47d32182b088fb631b0534e1d284945

**Comment by offalynne** [comment]
@manekinekodesu @abdulahmad @evilwraith would you be able to grab a mapping of the Genesis 3/6b NSO gamepads with this driver ?

**Pull request merged**
