### PR TITLE
Fixed one axis for 8BitDo SN30 Pro

### PR DESCRIPTION
**Pull request by FrodeSolheim**
Verified with latest firmware for the controller

### CODE REVIEW

**Comment by p-groarke** [comment]
@offalynne Would you like to double check this one? I can't remember if it was part of your large PR with 8bitdo controllers.

**Comment by FrodeSolheim** [comment]
Always a good idea to doublecheck :) For reference, I created my config with 8BitDo SN30 Pro firmware v1.33 on macOS 10.14.6.

**Comment by offalynne** [comment]
looks good to me

**Comment by p-groarke** [comment]
thx!

**Pull request merged**
