### PR TITLE
Update gamecontrollerdb.txt

### PR DESCRIPTION
**Pull request by prakashguptaCTL**
03000000632500008005000000010000,Redgear,platform:Mac OS X,a:b2,b:b1,x:b3,y:b0,back:b8,guide:b9,start:b6,leftstick:-a1,rightstick:-a3,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,-leftx:-a0,+lefty:+a1,rightx:a2,-righty:+a3,righttrig
WhatsApp Image 2022-07-03 at 11 23 05 PM
ger:b7

### CODE REVIEW

**Comment by offalynne** [comment]
leftstick and rightstick mappings are incorrect (they should be buttons when the thumbstick is clicked, not axis) and the lefttrigger mapping is missing. please correct the mapping if you would like it to be included.

please also provide a photo or product link with an image of the device.

**Comment by prakashguptaCTL** [comment]
> leftstick and rightstick mappings are incorrect (they should be buttons when the thumbstick is clicked, not axis) and the lefttrigger mapping is missing. please correct the mapping if you would like it to be included.
> 
> please also provide a photo or product link with an image of the device.

I am assigning by using Gamepad tool and pressing the keys according to the selection what I saw, I dont know where I am doing wrong. Can you please guide me how to correct it

**Comment by offalynne** [comment]
@prakashguptaCTL when the gamepad tool lights the left and right joystick up green for the first time (without an arrow) you need to click down on the thumbstick like a button without tilting it.

In order to get analogue values for the triggers, please press down on them slowly/lightly when promoted.

After you are done mapping, use the controller to make sure the readout matches the device correctly. If not, try again. While mapping, if something seems to go wrong (can’t map something, or a button is skipped), press “previous” as many times as necessary to correct the mapping before proceeding.

**Comment by prakashguptaCTL** [comment]
03000000632500008005000000010000,Redgear,platform:Mac OS X,a:b2,b:b1,x:b3,y:b0,back:b8,guide:b9,start:b6,leftstick:-a1,rightstick:-a3,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,-leftx:-a0,+lefty:+a1,rightx:a2,-righty:+a3,righttrigger:b7,

**Comment by offalynne** [comment]
@prakashguptaCTL that is the same mapping you posted above. It is not correct. Please follow the configurator instructions very carefully and read the directions in my previous reply.

**Comment by prakashguptaCTL** [comment]
I have done accordingly what you have said. Attaching the video for the same.
https://user-images.githubusercontent.com/81965879/177473246-ca66d632-f76e-47fb-902a-b2023c600a95.mp4

**Comment by offalynne** [comment]
OK, thanks for the video. Can you avoid using “Skip” ? Your map does not include left trigger. If the mapper is not providing button inputs for thumbstick click or lefttrigger, alternative steps follow.

Download this app: https://apps.apple.com/ca/app/controllers-lite/id673660806

Press every button and each joystick direction one at a time, making note of button/axes results in the app, and share your notes.

**Comment by prakashguptaCTL** [comment]
03000000632500008005000000010000,Redgear,platform:Mac OS X,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7

what about this one

**Comment by offalynne** [comment]
@prakashguptaCTL looks good, can you check what value you get for the `Home` button, please ? Either using the app in my reply above, or by making a new mapping and pressing `Home` for `a` (bottom face button) and skipping the rest so you can get the value quickly, so I can add that to the map ?

**Comment by prakashguptaCTL** [comment]
@offalynne  By using the 'Controllers Lite' App which you have suggested when I am pressing HOME button I am getting this Button 13: 1, it means I have pressed it.

**Comment by offalynne** [comment]
Looks good, thanks

**Pull request merged**
