### PR TITLE
Fixed the SDL tool name, and added a link to its source code

### PR DESCRIPTION
**Pull request by denilsonsa**
I previously had trouble trying to find the official SDL tool. With this commit, I'm using the correct name for the tool, as well as providing a direct link to the tool in the SDL repository.

### CODE REVIEW

**Comment by artcfox** [comment]
@offalynne 

I think this change should to be reverted. I recently had to use the game controller mapping tool, and was confused because it is not called gamepadmap for SDL2, that is the name of the SDL3 tool.

The original instructions were correct for SDL2, but since the main branch now tracks SDL3, you first need to switch to the SDL2 branch in order to find the controllermap tool: https://github.com/libsdl-org/SDL/blob/SDL2/test/controllermap.c

```
git clone https://github.com/libsdl-org/SDL
cd SDL
git checkout SDL2
cd test
./configure
make
./controllermap
```

**Comment by denilsonsa** [comment]
I wasn't aware the main branch was already for SDL 3. In such case, it might be worth keeping both the old name and the new name, for people who have either the version 2 or the version 3. In any case, the tool name should contain a link pointing to where the tool can be obtained.

**Comment by offalynne** [comment]
Feel free to open a PR with those changes

**Comment by offalynne** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/commit/8f2ddc0de02dfe4bd6b0b6cb22019153267b95dc

**Pull request merged**
