### PR TITLE
Fix mappings for Nintendo Switch Joy-Cons on Linux

### PR DESCRIPTION
**Pull request by joaorb64**
If compared to the line just above it, the mapping I changed is now identical to the other entry. Buttons X and Y were swapped.

### CODE REVIEW

**Comment by offalynne** [comment]
There is no difference in your commit except the order of keys in the mapping

**Comment by joaorb64** [comment]
Oops, you're correct. The thing I'm trying to fix is X and Y being swapped, but now I'm really confused with what made me upload the exact same mapping lol
I'll review it and get back to this thread.

**Comment by offalynne** [comment]
it’s possible gamepad tool isn‘t pulling the latest db version

**Comment by joaorb64** [comment]
Ok, just tested again with Gamepad tool.

- Unset environment variable
- Default mapping:
`060000007e0500000820000000000000,Nintendo Switch Combined Joy-Cons,a:b0,b:b1,x:b2,y:b3,back:b9,guide:b11,start:b10,leftstick:b12,rightstick:b13,leftshoulder:b5,rightshoulder:b6,dpup:b14,dpdown:b15,dpleft:b16,dpright:b17,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b7,righttrigger:b8,platform:Linux`
(X and Y are swapped)
- Remap from scratch:
`060000007e0500000820000000000000,Nintendo Switch Combined Joy-Cons,a:b0,b:b1,x:b3,y:b2,back:b9,guide:b11,start:b10,leftstick:b12,rightstick:b13,leftshoulder:b5,rightshoulder:b6,dpup:b14,dpdown:b15,dpleft:b16,dpright:b17,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b7,righttrigger:b8,platform:Linux`
(In fact, X and Y were swapped when I remapped)

**Comment by joaorb64** [comment]
One question, though: If I'm on Ubuntu running Retroarch (Flatpak), do you happen to know where does my mapping come from? I know it's out of this repo's and this issue's scope but asking for the chance.

**Comment by offalynne** [comment]
Nope 🥲
Worth asking on RA’s repo, tho

**Pull request closed without merging**
