### PR TITLE
adding large number of maps for different devices

### PR DESCRIPTION
**Pull request by offalynne**
most of these are mine but thanks to @heavyviper @ZackXu0 @Jaffacakelover for confirmation and a few additional maps

### CODE REVIEW

**Comment by offalynne** [comment]
@p-groarke 😉

**Comment by p-groarke** [comment]
Looks like great work, will review this w-e (at cppcon) :)

**Comment by Ordoviz** [comment]
Consider renaming _P380_ to _Saitek P380_ for consistency.

**Comment by p-groarke** [comment]
Wow what a drop! Thank you @offalynne @HeavyViper @ZackXu0 @Jaffacakelover for the amazing work and time put into this. 👍

**Pull request merged**
