### PR TITLE
Add disambiguating 2.26 format entries (Nebula Gamepad, ZM-X6, Rexus GX200)

### PR DESCRIPTION
**Pull request by RedDevilus**
*@offalynne edit Dec 22: using this PR to aggregate 2.26 format mappings for now*

***

Entries:
Nebula Gamepad, ZM-X6, Rexus GX200, GameSir G4 Pro 

This came with the Nebula Capsule 2 Projector (Nebula is a brand of Anker) and has 3 connection modes. This mapping is made with the Android one which connected via Bluetooth on my W10.

image

image

ZM-X6:

### CODE REVIEW

**Comment by RedDevilus** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/issues/635#issuecomment-1336296662

I do wonder if the mapping has less zeros than before as seen in this issue.

**Comment by offalynne** [comment]
what app did you use ? this issue my need reporting upstream

**Comment by offalynne** [comment]
@RedDevilus what is the name/description of the device before any edits ? The CRC16 (4e27) does not match `Nebula Gamepad`

**Comment by RedDevilus** [comment]
The original name is:
6 axis 15 button gamepad with hat switch

image

**Comment by offalynne** [comment]
Added 635

**Pull request merged**
