### PR TITLE
Update gamecontrollerdb.txt

### PR DESCRIPTION
**Pull request by mariuszk911**
8Bitdo SFC30 GamePad Bluetooth, fw 2.68

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Interesting, my pull request #80 adds the USB mode but I could not get Bluetooth mode to work. How did you do it? @mariuszk911

**Comment by mariuszk911** [comment]
try update to 2.68 beta5 firmware, and put gamepad in default mode (mode 1).

[http://forum.8bitdo.com/thread-1179-1-1.html](http://forum.8bitdo.com/thread-1179-1-1.html)

**Comment by gingerbeardman** [comment]
@mariuszk911 that did it! awesome, thanks.

**Comment by jmtd** [comment]
These mappings match what I get on my controller. If I start it in controller mode (Start+R) the name is "8Bitdo SFC30 GamePad Joystick" instead, but the mappings match.

**Pull request merged**
