### PR TITLE
Add Windows support for the Hori Mini PS4 controller for Windows

### PR DESCRIPTION
**Pull request by jdfeng**
Example of the controller in question: https://www.amazon.com/PlayStation-4-Mini-Wired-Gamepad/dp/B076MQ34PQ

I assume it is the same for Linux, but I don't have an environment to test that, so only submitting the Windows entry (sorry!)

### CODE REVIEW

**Comment by p-groarke** [comment]
Hey, no problem for the Linux version. I'm curious what tool you used to generate this, the GUID looks a bit different than usual?

**Comment by p-groarke** [comment]
Ah this is a SDL 2.0.4 mapping. Could you add it to the appropriate db (`older_releases\gamecontrollerdb_204.txt). If you could also generate a mapping with a new GUID using SDL 2.0.7 (or any version above) that would be great!

**Comment by jdfeng** [comment]
Will do!  (Sorry, git newb  - will cancel this request and submit a new one with the requested changes on top of the master branch.)

**Comment by jdfeng** [comment]
(Thank you very much for your help!)

**Comment by p-groarke** [comment]
No problem, everyone has to start somewhere :)

**Pull request closed without merging**
