### PR TITLE
Update to gamecontrollerdb.txt

### PR DESCRIPTION
**Pull request by tonedef71**
... to correct the right trigger button assignment (b5) and provide the proper manufacturer name of the game controller (iNNEXT). Moved the mapping string to the appropriate lexicographical-ordered name position within the file.

### CODE REVIEW

**Comment by offalynne** [comment]
@tonedef71 unfortunately there are a few variants of this pad with a variety of mapping differences, including Retroflag and “Next” as well as the iNnext pad you have on hand. i do believe the one already in the DB to be the most common. notice it’s mapped the same on all 3 platforms, and (via git blame) comes from upstream.

udev (linux) and dinput (windows) buttons are almost always equivalent and here’s a map from retroarch that  matches what’s already in the db: https://github.com/libretro/retroarch-joypad-autoconfig/blob/ad9623e86eb84c6454cfb2a76529d2315a89868b/udev/iNNEXT%20SNES%20Gamepad.cfg

i also have 2 of these pads that map the same as the what’s currently in the db, as well as a saturn-style pad with matching guid whose mapping is a superset of this one.

this is one of the downsides of the similar boards used in mass produced knockoffs with assembly differences overlapping, unfortunately.

i’ll close shortly since there’s no good way to resolve this, but if you want to provide more info about your device, please share a dump using lsusb on linux or USB Tree View (https://www.uwe-sieber.de/usbtreeview_e.html) on Windows in case there may be a way to disambiguate it in the future.

**Comment by tonedef71** [comment]
It is a shame that several controllers share the exact same UUID.  I'm wondering... since gamecontrollerdb.txt is simply a text file, is there any reason why there cannot be multiple entries present in this file which have the same UUID (i.e. variants)?  The name of the controller could serve as the distinguishing field (in the case of my USB game controller, the name is "iNNEXT SNES USB Controller Gamepad Joystick").

An application like [gamepadtool](http://generealarcade.com/gamepadtool/) can provide multiple entries in a dropdown control loaded from _gamecontrollerdb.txt_ which the user can pick from.

If this is acceptable, then I will commit and submit a new pull request with an update that inserts my entire mapping string as a new entry, instead of as a replacement for the existing one.

**Comment by offalynne** [comment]
I deleted my previous comment as I realized I made a few mistaken assumptions, sorry for breaking the flow of conversation here. I actually believe your map change is correct -- if you could find a way to confirm on Mac/Linux as well to keep them all in parity that would be ideal!

**Comment by offalynne** [comment]
>  is there any reason why there cannot be multiple entries present in this file which have the same UUID
This is by design. The DB is intended to provide individual maps per GUID for devices where they are relatively reliably consistent. We do not curate duplicates. There is code in SDL itself to handle name-based exceptions on a per-device basis, and it's out of scope here. Devices that have no reliably consistent map between identical GUIDs are removed.

If you want to add disambiguation you can handle it in your own project, or take it upstream to SDL.

**Comment by tonedef71** [comment]
The mapping string which I am providing is for [a USB game controller which is still being sold today on Amazon](https://www.amazon.com/iNNEXT-Controller-Joystick-Gamestick-Raspberry/dp/B0728DYPGM) (as a matter of fact, I purchased a pair of these USB controllers back in May 2018).  According to the vendor's description, it should work identically on the following operating systems: Windows 98/ME/Vista/2000/2003/XP/7/8/8.1/10; GNU/Linux; Ubuntu; Mac OS X and beyond.

**Comment by offalynne** [comment]
It would be best if this could be resolved upstream.

I suggest you take this directly to SDL if you're unable to confirm yourself using MacOS and Linux, perhaps Sam Latinga still has the device on hand to confirm. The commit in question is here http://lists.libsdl.org/pipermail/commits-libsdl.org/2017-January/001271.html

You can file a bug here https://bugzilla.libsdl.org
Or open discussion here https://discourse.libsdl.org

**Comment by tonedef71** [comment]
Thank you for the links and information.  

I have no current affiliation with the SDL project and have no intention to get involved with it.  Using the GamePadTool on Windows to generate the mapping string for my USB controller, I simply made a single correction to one setting: the right trigger button.  I thought the considerate thing to do would be to share my change with the greater community.  I have the ability to confirm the controller mapping on Windows and *nix, but I have no means by which to do so on MacOS.

Submitting a pull request to this GitHub repo is about as far as I am willing to go to contribute to this project.  If you are willing to allow my mapping string a place in gamecontrollerdb.txt as a commented-out entry, that would be OK with me.  If you prefer not to include it in gamecontrollerdb.txt at all, that is OK with me, too.  

Best regards.

**Comment by offalynne** [comment]
> I have the ability to confirm the controller mapping on Windows and *nix
Can you confirm on Linux and update the PR?

**Comment by offalynne** [comment]
After a little more digging I've found precedent for both `b5` and `b6` on right shoulder button, though most frequently it seems to be configured to the latter. Some users complain of inverted axes, so likely this is down to manufacturer differences.

Retro Games Ltd's C64 microconsole packages a modified map that seems to acknowledge the two shoulder mappings by including both:
03000000790000001100000010010000,USB GamepadChris,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftx:a0,lefty:a1,lefttrigger:b4,*righttrigger:b5,righttrigger:b6*,platform:Linux,

SDL's GUID generation occasionally differentiates pads on Mac /Linux that would conflated on Windows so you're welcome to resubmit if you find a unique GUID on another platform that doesn't collide with existing maps.

**Comment by tonedef71** [comment]
I ran the Linux version of the GamepadTool and the GUID it generated for my gamepad controller was slightly different from what the Windows version of the GamepadTool generated (the new GUID ends with the numbers "10010000".  I'm not sure why the Windows and Linux global IDs are different; is that normal?

Here is the full controller mapping string generated with the GUID generated by the Linux version of the GamepadTool:

030000001008000001e5000010010000,iNNEXT SNES Controller Gamepad Joystick,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:-a1,dpdown:+a1,dpleft:-a0,dpright:+a0,platform:Linux,

I also ran the Windows version of that UsbTreeView tool to retrieve information about the USB gamepad controller:
+++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Input Device
Device Path              : \\?\USB#VID_0810&PID_E501#5&19b80534&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-4
Device ID                : USB\VID_0810&PID_E501\5&19B80534&0&1
Hardware IDs             : USB\VID_0810&PID_E501&REV_0106 USB\VID_0810&PID_E501
Driver KeyName           : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0019 (GUID_DEVCLASS_HIDCLASS)
Driver                   : \SystemRoot\System32\drivers\hidusb.sys (Version: 10.0.19041.1  Date: 2019-12-07)
Driver Inf               : C:\WINDOWS\inf\input.inf
Legacy BusType           : PNPBus
Class                    : HIDClass
Class GUID               : {745a17a0-74d3-11d0-b6fe-00a0c90f57da} (GUID_DEVCLASS_HIDCLASS)
Service                  : HidUsb
Enumerator               : USB
Location Info            : Port_#0001.Hub_#0001
Location IDs             : PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(1), ACPI(_SB_)#ACPI(PCI0)#ACPI(XHC_)#ACPI(RHUB)#ACPI(HS01)
Container ID             : {9c07cabf-47f7-11eb-9cbd-94b86dfa3597}
Manufacturer Info        : (Standard system devices)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Status                   : 0x0180600A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
HcDisableSelectiveSuspend: 0
EnableSelectiveSuspend   : 0
SelectiveSuspendEnabled  : 0
EnhancedPowerMgmtEnabled : 1
IdleInWorkingState       : 0
WakeFromSleepState       : 0
Power State              : D0 (supported: D0, D3, wake from D0)
 Child Device 1          : HID-compliant game controller
  Device Path            : \\?\HID#VID_0810&PID_E501#6&b585533&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\00000109
  Device ID              : HID\VID_0810&PID_E501\6&B585533&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0020 (GUID_DEVCLASS_HIDCLASS)

---------------- Connection Information ---------------
Connection Index         : 0x01 (Port 1)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01 (Configuration 1)
Device Address           : 0x06 (6)
Is Hub                   : 0x00 (no)
Device Bus Speed         : 0x00 (Low-Speed)
Number Of Open Pipes     : 0x01 (1 pipe to data endpoints)
Pipe[0]                  : EndpointID=1  Direction=IN   ScheduleOffset=0  Type=Interrupt
Data (HexDump)           : 01 00 00 00 12 01 00 01 00 00 00 08 10 08 01 E5   ................
                           06 01 00 02 00 01 01 00 00 06 00 01 00 00 00 01   ................
                           00 00 00 07 05 81 03 08 00 0A 00 00 00 00         ..............

--------------- Connection Information V2 -------------
Connection Index         : 0x01 (1)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes, port supports USB 1.1)
 Usb200                  : 1 (yes, port supports USB 2.0)
 Usb300                  : 0 (no, port not supports USB 3.0) -> but Companion Port 1-17 does
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Device is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Device is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Device is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Device is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00
Data (HexDump)           : 01 00 00 00 10 00 00 00 03 00 00 00 00 00 00 00   ................

    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x100 (USB Version 1.00)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x08 (8 bytes)
idVendor                 : 0x0810 (Personal Communication Systems, Inc.)
idProduct                : 0xE501
bcdDevice                : 0x0106
iManufacturer            : 0x00 (No String Descriptor)
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "usb gamepad           "
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 00 01 00 00 00 08 10 08 01 E5 06 01 00 02   ................
                           00 01                                             ..

------------------ Configuration Descriptor -------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x0022 (34 bytes)
bNumInterfaces           : 0x01 (1 Interface)
bConfigurationValue      : 0x01 (Configuration 1)
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0x80
 D7: Bus Powered         : 0x01 (yes)
 D6: Self Powered        : 0x00 (no)
 D5: Remote Wakeup       : 0x00 (no)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0xFA (500 mA)
Data (HexDump)           : 09 02 22 00 01 01 00 80 FA 09 04 00 00 01 03 00   ..".............
                           00 00 09 21 10 01 21 01 22 59 00 07 05 81 03 08   ...!..!."Y......
                           00 0A                                             ..

---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)
Data (HexDump)           : 09 04 00 00 01 03 00 00 00                        .........

------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0110 (HID Version 1.10)
bCountryCode             : 0x21 (33 = US)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 10 01 21 01 22 59 00                        .!..!."Y.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0059 (89 bytes)
Error reading descriptor : ERROR_INVALID_PARAMETER (due to a obscure limitation of the Win32 USB API, see UsbTreeView.txt)

----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0008
bInterval                : 0x0A (10 ms)
Data (HexDump)           : 07 05 81 03 08 00 0A                              .......

-------------------- String Descriptors -------------------
------ String Descriptor 0 ------
bLength                  : 0x04 (4 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language ID[0]           : 0x0409 (English - United States)
Data (HexDump)           : 04 03 09 04                                       ....
------ String Descriptor 2 ------
bLength                  : 0x2E (46 bytes)
bDescriptorType          : 0x03 (String Descriptor)
Language 0x0409          : "usb gamepad           "  *!*CAUTION  trailing space characters
Data (HexDump)           : 2E 03 75 00 73 00 62 00 20 00 67 00 61 00 6D 00   ..u.s.b. .g.a.m.
                           65 00 70 00 61 00 64 00 20 00 20 00 20 00 20 00   e.p.a.d. . . . .
                           20 00 20 00 20 00 20 00 20 00 20 00 20 00          . . . . . . .

**Comment by offalynne** [comment]
> I'm not sure why the Windows and Linux global IDs are different; is that normal?

Yes.

> UsbTreeView dump

Thank you!

**Comment by AliceLR** [comment]
> I'm not sure why the Windows and Linux global IDs are different; is that normal?

The last 8 hex digits of the GUID are generated from the driver version number and tend to be different between different platforms.

**Pull request closed without merging**
