### PR TITLE
Add Raphnet N64 V3

### PR DESCRIPTION
**Pull request by amiosi**

### CODE REVIEW

**Comment by FrostKnight** [comment]
Hey, I just wanted to mention, for some reason, I tried using your config as suggested here:

https://github.com/fgsfdsfgs/perfect_dark/issues/518

Z button does not work with this nor does start or control stick.

does raphnet n64 v3 have a linux compatible entry? I only see it in windows for some reason. But I know it works for linux also. 

I have used it on mupen64plus. 

Anywho I am using debian, can you help?

**Comment by offalynne** [comment]
@FrostKnight look at the README and generate a working mapping from your end

**Comment by FrostKnight** [comment]
> @FrostKnight look at the README and generate a working mapping from your end

I see what four of the buttons do on your readme, the A and B for example, but do you have a full list of what pertains do what? 

I am impressed at the fast response though

**Comment by offalynne** [comment]
Just run the app and map follow the prompts sensibly. Post your results and I'll correct any issues.

**Comment by FrostKnight** [comment]
> Just run the app and follow the prompts sensibly. Post your results and I'll correct any issues.

I ran the app and copied mappings and I got this:

"030000009b2800006300000001010000,raphnet technologies Dual GC/N64 to USB v3.6,a:b0,b:b1,x:b4,y:b3,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:b8,righttrigger:b9"

Seems I have the dual n64/GC one. weird

**Comment by offalynne** [comment]
> sensibly

> `x:b4,y:b3,back:b10,guide:b12,`

what are these ?

**Comment by FrostKnight** [comment]
> > sensibly
> 
> what are these ?
> 
> > `x:b4,y:b3,back:b10,guide:b12,` [...] `leftstick:b13,rightstick:b14`

Idk... I just used the tool mentioned on your page, the old one to copy the mappings it detected.

**Comment by offalynne** [comment]
1. Download and run this https://www.generalarcade.com/gamepadtool/
2. Click "Create A New Mapping"
3. Press the buttons on your controller that correspond to the onscreen prompts: Xbox A > N64 A, Xbox B > N64 B, Xbox left trigger > N64 Z, Xbox right stick directions > N64 C buttons, etc.
4. Click "Skip" for onscreen prompts indicating buttons that are not on the N64 controller
5. When you are done, press buttons and thumbstick to confirm with the onscreen graphic you have mapped everything correctly. If not, start again from 2.
6. Click "Copy Mapping String", open a new issue, and paste the mapping string in a text editor
7. Read the mapping string and confirm it makes sense. There is no reasonable way for you to map `x:b4,y:b3,back:b10,guide:b12, [...] leftstick:b13,rightstick:b14` as these buttons do not exist on an N64 controller. Please look at the data and think it through reasonably
9. If you have determined, on your end, with your controller in hand, and using your good sense that your mapping is correct, open a new issue or a PR with the data

If you need more help, read the README
If you're not able to clear this list, please do not create further noise on the issue.

**Comment by FrostKnight** [comment]
> > I wonder if antimicrox would be better
> 
> No.
> 
>     1. Download and run this https://www.generalarcade.com/gamepadtool/
> 
>     2. Click "Create A New Mapping"
> 
>     3. Press the buttons on your controller that correspond to the onscreen prompts: Xbox A > N64 A, Xbox B > N64 B, Xbox left trigger > N64 Z, Xbox right stick directions > N64 C buttons, etc.
> 
>     4. Click "Skip" for onscreen prompts indicating buttons that are not on the N64 controller
> 
>     5. When you are done, press buttons and thumbstick to confirm with the onscreen graphic you have mapped everything correctly. If not, start again from 2.
> 
>     6. Click "Copy Mapping String" and paste the mapping string in a text editor
> 
>     7. Read the mapping string and confirm it makes sense. There is no reasonable way for you to map `x:b4,y:b3,back:b10,guide:b12, [...] leftstick:b13,rightstick:b14` as these buttons do not exist on an N64 controller. Please look at the data and think it through reasonably
> 
>     8. If you have determined, on your end, with your controller in hand, and using your good sense that your mapping is correct, open a new issue or a PR with the data
> 
> 
> If you need more help, read the README If you're not able to clear this list, please do not create further noise on the issue.

I actually just found time to check and I noticed, when I press the Z button, nothing registers with this controller. Its rather strange...  

Also, the diagram of the controller looks wrong. N64 controllers don't look like that and therefore its confusing to try to input certain things.

Anywho though, the Z button is 100% nonworking.

**Pull request merged**
